/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bikestock;
        
import Data.dbcon;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Lenovo
 */
public class customer extends javax.swing.JFrame {

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
  
    @SuppressWarnings("unchecked")
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcus = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcontact1 = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        tctnic = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NICvalidate = new javax.swing.JLabel();
        Teleponevalidate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsave.setBackground(new java.awt.Color(102, 102, 255));
        btnsave.setForeground(new java.awt.Color(255, 255, 204));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 110, 30));

        jLabel5.setText("EMAIL");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 76, -1));

        tblcus.setBackground(new java.awt.Color(153, 153, 255));
        tblcus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIC", "NAME", "ADDRESS", "EMAIL", "CONTACT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblcus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcus);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 700, 210));

        jLabel4.setText("CONTACT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 76, -1));

        jLabel3.setText("ADDRESS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 76, -1));

        jLabel1.setText("NAME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 37, -1));

        jLabel2.setText("NIC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 37, -1));

        txtcontact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontact1KeyPressed(evt);
            }
        });
        jPanel1.add(txtcontact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 191, -1));

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 191, -1));
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 191, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 191, -1));

        tctnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tctnicKeyPressed(evt);
            }
        });
        jPanel1.add(tctnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 191, -1));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 255));
        btnUpdate.setForeground(new java.awt.Color(204, 255, 204));
        btnUpdate.setText("Update Record");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 110, 30));

        btnDelete.setBackground(new java.awt.Color(102, 102, 255));
        btnDelete.setForeground(new java.awt.Color(255, 255, 204));
        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel6.setText("CUSTOMER");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("BACK TO MAIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(186, 186, 186)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 70));

        NICvalidate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NICvalidate.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(NICvalidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 180, 20));

        Teleponevalidate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Teleponevalidate.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(Teleponevalidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 180, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void NIVvalidate(){
         
       String  nic=tctnic.getText();
       
       if(nic.length()<10){
           
           NICvalidate.setText("NIC should be 10 or 11 numbers");
           
       }
       else{
           NICvalidate.setText("");
       }
      
}
      public void Mobilevalidate(){
           
            String contact=txtcontact1.getText();
            
            if(contact.length()==9){
                
           
            Teleponevalidate.setText("");  
            }
            else{
                
               Teleponevalidate.setText("Mobile Number should be 10 digits");
               //JOptionPane.showMessageDialog(null,"Mobile Number should be 10 digits");
            }
            
       }
    
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        
          String NIC=tctnic.getText();
          String name=txtname.getText();
          String add=txtaddress.getText();
          String mail=txtemail.getText();
          String contact=txtcontact1.getText(); 
          
          
          if(NIC.equals("")||name.equals("")||add.equals("")||mail.equals("")||contact.equals("")){
              
              
               JOptionPane.showMessageDialog(null,"Please fill Fealds");
          }
          else{
          try{
           
        Statement st=dbcon.createDbConnection().createStatement();
        int row_count=st.executeUpdate("INSERT INTO customer VALUES('"+NIC+"','"+name+"','"+add+"','"+contact+"','"+mail+"')");
        if(row_count>0)
         {
            JOptionPane.showMessageDialog(null, "Record Insert");  
            
         }
        else
         {
            JOptionPane.showMessageDialog(null, "ERROR");
         }
        
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
             
      }
          

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
       try
        {
           
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.addColumn("NIC");
        dtm.addColumn("NAME");
        dtm.addColumn("ADDRESS");
        dtm.addColumn("EMAIL");
        dtm.addColumn("CONTACT");
        
        Statement st=dbcon.createDbConnection().createStatement();
        java.sql.ResultSet rst=st.executeQuery("select * from customer");
       while(rst.next())
            {
                String[] value=new String[5];
                value[0]=rst.getString(1);
                value[1]=rst.getString(2);
                value[2]=rst.getString(3);
                value[3]=rst.getString(4);
                value[4]=rst.getString(5);
                dtm.addRow(value);
            }
         tblcus.setModel(dtm);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }  
        
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
          String NIC=tctnic.getText();
          
      try
        {    
        Statement st=dbcon.createDbConnection().createStatement();
        int row_count=st.executeUpdate("DELETE FROM customer where NIC='"+NIC+"'");
        if(row_count>0)
         {
            JOptionPane.showMessageDialog(null, "Record DELETED");  
         }
        else
         {
            JOptionPane.showMessageDialog(null, "ERROR");
         }
        
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
             
          String NIC=tctnic.getText();
          String name=txtname.getText();
          String add=txtaddress.getText();
          String mail=txtemail.getText();
          String contact=txtcontact1.getText();
      try
        {    
        Statement st=dbcon.createDbConnection().createStatement();
        int row_count=st.executeUpdate("UPDATE customer set name='"+name+"',address='"+add+"',email='"+mail+"',contact='"+contact+"'where NIC='"+NIC+"'");
        if(row_count>0)
         {
            JOptionPane.showMessageDialog(null, "Record Updated");  
         }
        else
         {
            JOptionPane.showMessageDialog(null, "ERROR");
         }
        
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }


        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblcusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcusMouseClicked
     
        DefaultTableModel model=(DefaultTableModel)tblcus.getModel();
        int selectedRowIndex=tblcus.getSelectedRow();
        
        tctnic.setText(model.getValueAt(selectedRowIndex,0).toString());
        txtname.setText(model.getValueAt(selectedRowIndex,1).toString());
        txtaddress.setText(model.getValueAt(selectedRowIndex,2).toString());
        txtemail.setText(model.getValueAt(selectedRowIndex,3).toString());
        txtcontact1.setText(model.getValueAt(selectedRowIndex,4).toString());
        
        
       
    }//GEN-LAST:event_tblcusMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Main1 mi= new Main1();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tctnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tctnicKeyPressed
        // TODO add your handling code here:
        NIVvalidate();
        
        
        
    }//GEN-LAST:event_tctnicKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtcontact1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontact1KeyPressed
        // TODO add your handling code here:
         Mobilevalidate();
    }//GEN-LAST:event_txtcontact1KeyPressed
         
    
    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NICvalidate;
    private javax.swing.JLabel Teleponevalidate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcus;
    private javax.swing.JTextField tctnic;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcontact1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
