/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bikestock;

/**
 *
 * @author Lenovo
 */
import Data.dbcon;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class DIO extends javax.swing.JFrame {

    /**
     * Creates new form DIO
     */
    public DIO() {
        initComponents();
        avelable();
    }
     Invoice I=new Invoice();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        txtengnum44 = new javax.swing.JTextField();
        txtchassnum4 = new javax.swing.JTextField();
        txtweight6 = new javax.swing.JTextField();
        cmbcapa4 = new javax.swing.JComboBox<>();
        cmbfuelcapa5 = new javax.swing.JComboBox<>();
        cmbcolor4 = new javax.swing.JComboBox<>();
        txttrance4 = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPaltina2 = new javax.swing.JTable();
        btnsave2 = new javax.swing.JButton();
        btnupdate2 = new javax.swing.JButton();
        btnview2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        coun = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(txtengnum44, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 122, 150, -1));
        jPanel6.add(txtchassnum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 162, 150, -1));
        jPanel6.add(txtweight6, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 202, 150, -1));

        cmbcapa4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100CC", "125CC", "150CC", " " }));
        jPanel6.add(cmbcapa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 250, 150, -1));

        cmbfuelcapa5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8L", "10L", "12L" }));
        jPanel6.add(cmbfuelcapa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 122, 150, -1));

        cmbcolor4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLACK", "BLUE", "BROWN", "MEROON", "RED", " " }));
        jPanel6.add(cmbcolor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 162, 150, -1));
        jPanel6.add(txttrance4, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 202, 150, 30));
        jPanel6.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 250, 160, -1));

        jLabel20.setText("Engine Number");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 125, -1, -1));

        jLabel21.setText("Chasiss Number");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 165, -1, -1));

        jLabel22.setText("Weight");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 205, 63, -1));

        jLabel23.setText("Capacity");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 253, 50, -1));

        jLabel24.setText("Fuel Capacity");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 125, -1, -1));

        jLabel25.setText("Color");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 165, -1, -1));

        jLabel26.setText("Tracemisson");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 207, -1, 20));

        jLabel27.setText("Price");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 250, 40, -1));

        tblPaltina2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ENGINE NUMBER", "CHASSIS NUMBER", "WEIGHT", "CAPACITY", "FUEL CAPACITY", "COLOUR", "TRANCEMISSION", "PRICE", "STATUS UPDATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPaltina2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaltina2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPaltina2);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 368, 839, 170));

        btnsave2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsave2.setText("Save");
        btnsave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnsave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 325, -1, -1));

        btnupdate2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        btnupdate2.setText("Update Record");
        jPanel6.add(btnupdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        btnview2.setText("View");
        btnview2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnview2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setText("DIO");

        btnback.setBackground(new java.awt.Color(255, 0, 51));
        btnback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addGap(310, 310, 310)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnback))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 923, -1));

        coun.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jPanel6.add(coun, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 50, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 102));
        jLabel14.setText("NUMBER OF BIKES IN STOCK");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave2ActionPerformed
        // TODO add your handling code here:
        String eng=txtengnum44.getText();
        String chass=txtchassnum4.getText();
        String weight=txtweight6.getText();
        String capa=cmbcapa4.getSelectedItem().toString();
        String fuel=cmbfuelcapa5.getSelectedItem().toString();

        String color= cmbcolor4.getSelectedItem().toString();
        String trance=txttrance4.getText();
        float  price =Float.parseFloat(txtprice.getText());
        
          if(eng.equals("")||chass.equals("")||weight.equals("")||capa.equals("")||trance.equals("")||fuel.equals("")||color.equals("")){
             
          JOptionPane.showMessageDialog(null,"Please fill Fealds");   
             
         }
          else{
        try
        {
            Statement st=dbcon.createDbConnection().createStatement();
            int row_count=st.executeUpdate("INSERT INTO DIO VALUES('"+eng+"','"+chass+"','"+weight+"','"+capa+"','"+fuel+"','"+color+"','"+trance+"','"+price+"')");
            if(row_count>0)
            {
                JOptionPane.showMessageDialog(null, "Record Insert");
                avelable();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "ERROR");
            }

        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
            
             
         }
    }//GEN-LAST:event_btnsave2ActionPerformed

    private void btnview2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try
        {

            DefaultTableModel dtm=new DefaultTableModel();
            dtm.addColumn("ENGINE NUMBER");
            dtm.addColumn("CHASISS NUMBER");
            dtm.addColumn("WEIGHT");
            dtm.addColumn("CAPACITY");
            dtm.addColumn("FUEL CAPACITY");
            dtm.addColumn("COLOUR");
            dtm.addColumn("TRANCEMISSION");
            dtm.addColumn("PRICE");

            Statement st=dbcon.createDbConnection().createStatement();
            java.sql.ResultSet rst=st.executeQuery("select * from DIO");
            while(rst.next())
            {
                String[] value=new String[8];
                value[0]=rst.getString(1);
                value[1]=rst.getString(2);
                value[2]=rst.getString(3);
                value[3]=rst.getString(4);
                value[5]=rst.getString(6);
                value[6]=rst.getString(7);
                value[7]=rst.getString(8);

                dtm.addRow(value);
            }
            tblPaltina2.setModel(dtm);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnview2ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        honda b =new honda();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void tblPaltina2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaltina2MouseClicked
        // TODO add your handling code here:
         
          int index =  tblPaltina2.getSelectedRow();
        
        TableModel model = tblPaltina2.getModel();
        
        String engine2 = model.getValueAt(index, 0).toString();
        String price0 = model.getValueAt(index, 7).toString();
        
        
        I.setVisible(true);
        I.pack();
        I.setLocationRelativeTo(null);
        
        I.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
        
        I.txtengnum44.setText(engine2);
        I.price0.setText(price0);
    }//GEN-LAST:event_tblPaltina2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DIO().setVisible(true);
            }
        });
    }
     public void avelable(){
       
        try{
           Statement st=dbcon.createDbConnection().createStatement();
        java.sql.ResultSet rst=st.executeQuery("select count(*) from DIO");
       while(rst.next())
            {
               int count=rst.getInt(1);
               coun.setText(String.valueOf(count));
            } 
            
        }
        catch(Exception Ex){
           
              JOptionPane.showMessageDialog(null, Ex.getMessage());
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsave2;
    private javax.swing.JButton btnupdate2;
    private javax.swing.JButton btnview2;
    private javax.swing.JComboBox<String> cmbcapa4;
    private javax.swing.JComboBox<String> cmbcolor4;
    private javax.swing.JComboBox<String> cmbfuelcapa5;
    private javax.swing.JLabel coun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblPaltina2;
    private javax.swing.JTextField txtchassnum4;
    private javax.swing.JTextField txtengnum44;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txttrance4;
    private javax.swing.JTextField txtweight6;
    // End of variables declaration//GEN-END:variables
}
